version: '3.8'
services:
  web:
    image: pushpendrahpx/workitoffline
    build: backend/
    depends_on: 
      - postgresdb
    command: node server.js
    ports:
      - "3000:3000"
    environment:
      SERVER_NAME: mainserver

  postgresdb:
    build: postgresdb/
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres1
      - POSTGRES_DB=postgres 
    ports:
      - 5432:5432
    volumes: 
      - ./postgresdb_data:/var/lib/postgresql/data
      - ./postgresdb/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgresdb:
