version: '3.8'
services:
  web:
    image: pushpendrahpx/workitoffline
    build: backend/
    command: node app.js
    ports:
      - "3000:3000"
    environment:
      SERVER_NAME: mainserver

  postgresdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=googleuser
    ports:
      - 5432:5432
    volumes: 
      - postgresdb:/var/lib/postgresql/data

volumes:
  postgresdb: