FROM node

RUN mkdir -p /home/app/node_modules && chmod +x /home/app

WORKDIR /home/app

RUN ls 
RUN pwd

COPY package*.json /home/app/

RUN npm install

COPY . /home/app/

EXPOSE 3000

CMD [ "node", "app.js" ]